---
title: "Cars per day on roads of Toulouse"
author: "Akim van Eersel"
date: "2020-11-19"
output: ioslides_presentation
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##

```{r data, echo=FALSE, fig.height=6, fig.width=8, message=FALSE, warning=FALSE}
library(plotly)

if (!file.exists("data")){
      dir.create("data")
      fileURL <- "https://data.toulouse-metropole.fr/explore/dataset/comptages-routiers/download/?format=csv&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%3B"
      download.file(fileURL, destfile = "./data/comptages-routiers.csv", method = "auto")
}

trafic <- read.csv(file = "./data/comptages-routiers.csv", sep = ';')
date.comptage <- as.Date(trafic$Date.Comptage)
comptage <- trafic$Moyenne.Jours.ouvrÃ.s.par.semaine.

x <- list(title = "Measurement date")
y <- list(title = "Cars per day")

fig <- plot_ly(x = ~date.comptage, y = ~comptage, type = "scatter", mode = "markers",
        color = factor(trafic$AnnÃ.e))
fig <- fig %>% layout(xaxis = x, yaxis = y, title = "Cars per day in specific roads in Toulouse, France")
fig
```
